# Jutge AI Model Benchmark Configuration
models:
  - name: "Claude-Sonnet-4"
    provider: "openrouter"
    model_id: "anthropic/claude-sonnet-4"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Gemini-2.0-Flash-001"
    provider: "openrouter"
    model_id: "google/gemini-2.0-flash-001"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Gemini-2.5-Flash"
    provider: "openrouter"
    model_id: "google/gemini-2.5-flash"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "DeepSeek-Chat-V3-0324-Free"
    provider: "openrouter"
    model_id: "deepseek/deepseek-chat-v3-0324:free"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Gemini-2.5-Pro"
    provider: "openrouter"
    model_id: "google/gemini-2.5-pro"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 64000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Gemini-2.5-Flash-Preview-05-20"
    provider: "openrouter"
    model_id: "google/gemini-2.5-flash-preview-05-20"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "DeepSeek-Chat-V3-0324"
    provider: "openrouter"
    model_id: "deepseek/deepseek-chat-v3-0324"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Claude-3.7-Sonnet"
    provider: "openrouter"
    model_id: "anthropic/claude-3.7-sonnet"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Gemini-2.5-Flash-Lite-Preview-06-17"
    provider: "openrouter"
    model_id: "google/gemini-2.5-flash-lite-preview-06-17"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "DeepSeek-R1-0528-Free"
    provider: "openrouter"
    model_id: "deepseek/deepseek-r1-0528:free"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "GPT-4o-Mini"
    provider: "openrouter"
    model_id: "openai/gpt-4o-mini"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Mistral-Nemo"
    provider: "openrouter"
    model_id: "mistralai/mistral-nemo"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Gemini-2.5-Flash-Preview"
    provider: "openrouter"
    model_id: "google/gemini-2.5-flash-preview"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "GPT-4.1"
    provider: "openrouter"
    model_id: "openai/gpt-4.1"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "DeepSeek-R1-Free"
    provider: "openrouter"
    model_id: "deepseek/deepseek-r1:free"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "GPT-4.1-Mini"
    provider: "openrouter"
    model_id: "openai/gpt-4.1-mini"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Gemini-2.0-Flash-Lite-001"
    provider: "openrouter"
    model_id: "google/gemini-2.0-flash-lite-001"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Llama-3.3-70B-Instruct"
    provider: "openrouter"
    model_id: "meta-llama/llama-3.3-70b-instruct"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Llama-4-Maverick"
    provider: "openrouter"
    model_id: "meta-llama/llama-4-maverick"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Claude-Opus-4"
    provider: "openrouter"
    model_id: "anthropic/claude-opus-4"
    api_key: null  # Will use OPENROUTER_API_KEY environment variable
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32000
    temperature: 0.1
    timeout: 30
    enabled: true

problem_sets:
  hello_world:
    - "P68688_en"  # Hello world!

  basic_algorithms:
    - "P68688_en"   # Hello world!
    - "P62421_en"   # Three words
    - "P57548_en"   # Sum of two integer numbers
    - "P41221_en"   # Sum of three integer numbers
    - "P56118_en"   # Maximum of two integer numbers
    - "P52847_en"   # Maximum of three different integer numbers
    - "P90615_en"   # Maximum of three integer numbers
    - "P15613_en"   # Temperatures
    - "P48107_en"   # Integer division and remainder of two natural numbers

  medium_problems:
    - "P68688_en"   # Hello world!
    - "P62421_en"   # Three words
    - "P57548_en"   # Sum of two integer numbers
    - "P41221_en"   # Sum of three integer numbers
    - "P56118_en"   # Maximum of two integer numbers
    - "P90615_en"   # Maximum of three integer numbers
    - "P92351_en"   # Integer division and remainder of an integer number by a natural number
    - "P98960_en"   # Uppercase and lowercase letters
    - "P42042_en"   # Classification of characters (1)
    - "P90226_en"   # Comparison of words
    - "P92613_en"   # Rounding
    - "P37469_en"   # Time decomposition (1)
    - "P34279_en"   # Add one second
    - "P81629_en"   # Minimum change

  advanced_problems:
    - "P61634_en"   # Leap years
    - "P51126_en"   # Intervals (1)
    - "P56559_en"   # Intervals (2)
    - "P89265_en"   # Intervals (3)
    - "P58294_en"   # The answer
    - "P42042_en"   # Classification of characters (1)
    - "P37469_en"   # Time decomposition (1)
    - "P34279_en"   # Add one second
    - "P92351_en"   # Integer division and remainder of an integer number by a natural number
    - "P98960_en"   # Uppercase and lowercase letters

  one_problem:
    - "P30170_en"   # Repeated words

  custom_problems:
    - "P30170_en"
    - "P70093_en"
    - "P12284_en"

  learning_to_program_1:
    - "P68688_en"
    - "P62421_en"
    - "P57548_en"
    - "P41221_en"
    - "P56118_en"
    - "P52847_en"
    - "P90615_en"
    - "P15613_en"
    - "P48107_en"
    - "P92351_en"
    - "P98960_en"
    - "P42042_en"
    - "P90226_en"
    - "P92613_en"
    - "P37469_en"
    - "P34279_en"
    - "P81629_en"
    - "P61634_en"
    - "P51126_en"
    - "P56559_en"
    - "P89265_en"
    - "P58294_en"
    - "P37500_en"
    - "P59875_en"
    - "P59539_en"
    - "P97156_en"
    - "P36668_en"
    - "P69277_en"
    - "P31170_en"
    - "P50327_en"
    - "P28754_en"
    - "P60816_en"
    - "P55622_en"
    - "P97969_en"
    - "P79784_en"
    - "P78142_en"
    - "P39057_en"
    - "P67723_en"
    - "P96767_en"
    - "P72986_en"
    - "P29448_en"
    - "P35547_en"
    - "P43850_en"
    - "P79817_en"
    - "P90133_en"
    - "P33839_en"
    - "P29973_en"
    - "P72484_en"
    - "P42280_en"
    - "P13623_en"
    - "P19991_en"

  learning_to_program_2:
    - "P80660_en"
    - "P58153_en"
    - "P24080_en"
    - "P34080_en"
    - "P39359_en"
    - "P35080_en"
    - "P61061_en"
    - "P37760_en"
    - "P38045_en"
    - "P96275_en"
    - "P57846_en"
    - "P73231_en"
    - "P57474_en"
    - "P17913_en"
    - "P58653_en"
    - "P88790_en"
    - "P57852_en"
    - "P96564_en"
    - "P55722_en"
    - "P77686_en"
    - "P95401_en"
    - "P58459_en"
    - "P18777_en"
    - "P34091_en"
    - "P95972_en"
    - "P65437_en"
    - "P98458_en"
    - "P32954_en"
    - "P22654_en"
    - "P21281_en"
    - "P99541_en"
    - "P24381_en"
    - "P71649_en"
    - "P59652_en"
    - "P93157_en"
    - "P12509_en"
    - "P61384_en"
    - "P42523_en"
    - "P51222_en"
    - "P35537_en"
    - "P96965_en"
    - "P61930_en"
    - "P22467_en"
    - "P43557_en"
    - "P56549_en"
    - "P93533_en"
    - "P62467_en"
    - "P79860_en"
    - "P10694_en"

  learning_to_program_3:
    - "P20006_en"
    - "P45102_en"
    - "P85288_en"
    - "P26041_en"
    - "P52926_en"
    - "P92998_en"
    - "P38877_en"
    - "P42156_en"
    - "P89336_en"
    - "P37257_en"
    - "P23001_en"
    - "P71753_en"
    - "P17179_en"
    - "P73501_en"
    - "P33371_en"
    - "P89851_en"
    - "P81585_en"
    - "P18298_en"
    - "P29253_en"
    - "P89872_en"
    - "P75149_en"
    - "P89078_en"
    - "P39225_en"
    - "P27411_en"
    - "P65103_en"
    - "P48713_en"
    - "P50095_en"
    - "P31111_en"
    - "P35957_en"
    - "P12061_en"
    - "P36430_en"
    - "P18203_en"
    - "P67454_en"
    - "P87523_en"
    - "P26492_en"
    - "P76024_en"
    - "P42672_en"
    - "P74859_en"
    - "P89979_en"
    - "P49603_en"
    - "P11916_en"
    - "P94857_en"
    - "P84735_en"
    - "P20262_en"
    - "P15695_en"
    - "P40593_en"
    - "P87198_en"
    - "P46903_en"
    - "P39308_en"
    - "P19724_en"

  learning_to_program_4:
    - "P98577_en"
    - "P67171_en"
    - "P92845_en"
    - "P14130_en"
    - "P67268_en"
    - "P78548_en"
    - "P99133_en"
    - "P71310_en"
    - "P11725_en"
    - "P50497_en"
    - "P24301_en"
    - "P63414_en"
    - "P87920_en"
    - "P28318_en"
    - "P26374_en"
    - "P27498_en"
    - "P61473_en"
    - "P73039_en"
    - "P44243_en"
    - "P52233_en"
    - "P99555_en"
    - "P87801_en"
    - "P16893_en"
    - "P26585_en"
    - "P92844_en"
    - "P56358_en"
    - "P90532_en"
    - "P34438_en"
    - "P48763_en"
    - "P81966_en"
    - "P29094_en"
    - "P81602_en"
    - "P98179_en"
    - "P41412_en"
    - "P89124_en"
    - "P90664_en"
    - "P70093_en"
    - "P16072_en"
    - "P46584_en"
    - "P66257_en"
    - "P65538_en"
    - "P30170_en"
    - "P35941_en"
    - "P26100_en"
    - "P27283_en"
    - "P91173_en"
    - "P12284_en"

# Benchmark settings
default_language: "G++17"  # Default programming language for benchmarks
max_attempts_per_problem: 1
timeout_per_problem: 300  # 5 minutes
retry_on_failure: true
max_retries: 2
save_detailed_logs: true
output_format: "json"  # "json", "csv", "html"
parallel_strategy: "full"  # "full", "models", "sequential"

# Raw response logging for debugging (helps analyze extraction failures like Gemini 2.5 Pro)
save_raw_responses: true  # Enable to save AI responses for debugging
raw_responses_dir: "results/raw_responses"  # Directory to save raw responses
save_raw_on_failure_only: false  # Set to true to only save when extraction/execution fails 