# Jutge AI Model Benchmark Configuration
models:
  - name: "GPT-4o-mini"
    provider: "openai"
    model_id: "gpt-4o-mini"
    api_key: null  # Will use OPENAI_API_KEY environment variable
    max_tokens: 2000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "GPT-4o"
    provider: "openai"
    model_id: "gpt-4o"
    api_key: null  # Will use OPENAI_API_KEY environment variable
    max_tokens: 2000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Claude-3.5-Sonnet"
    provider: "anthropic"
    model_id: "claude-3-5-sonnet-20241022"
    api_key: null  # Will use ANTHROPIC_API_KEY environment variable
    max_tokens: 2000
    temperature: 0.1
    timeout: 30
    enabled: false  # Disabled by default, enable if API key is available

  - name: "Gemini-Pro"
    provider: "google"
    model_id: "gemini-pro"
    api_key: null  # Will use GOOGLE_API_KEY environment variable
    max_tokens: 2000
    temperature: 0.1
    timeout: 30
    enabled: false  # Disabled by default, enable if API key is available

problem_sets:
  hello_world:
    - "P68688"  # Hello world!

  basic_algorithms:
    - "P68688"   # Hello world!
    - "P62421"   # Three words
    - "P57548"   # Sum of two integer numbers
    - "P41221"   # Sum of three integer numbers
    - "P56118"   # Maximum of two integer numbers
    - "P52847"   # Maximum of three different integer numbers
    - "P90615"   # Maximum of three integer numbers
    - "P15613"   # Temperatures
    - "P48107"   # Integer division and remainder of two natural numbers

  medium_problems:
    - "P68688"   # Hello world!
    - "P62421"   # Three words
    - "P57548"   # Sum of two integer numbers
    - "P41221"   # Sum of three integer numbers
    - "P56118"   # Maximum of two integer numbers
    - "P90615"   # Maximum of three integer numbers
    - "P92351"   # Integer division and remainder of an integer number by a natural number
    - "P98960"   # Uppercase and lowercase letters
    - "P42042"   # Classification of characters (1)
    - "P90226"   # Comparison of words
    - "P92613"   # Rounding
    - "P37469"   # Time decomposition (1)
    - "P34279"   # Add one second
    - "P81629"   # Minimum change

  advanced_problems:
    - "P61634"   # Leap years
    - "P51126"   # Intervals (1)
    - "P56559"   # Intervals (2)
    - "P89265"   # Intervals (3)
    - "P58294"   # The answer
    - "P42042"   # Classification of characters (1)
    - "P37469"   # Time decomposition (1)
    - "P34279"   # Add one second
    - "P92351"   # Integer division and remainder of an integer number by a natural number
    - "P98960"   # Uppercase and lowercase letters

# Benchmark settings
max_attempts_per_problem: 1
timeout_per_problem: 300  # 5 minutes
retry_on_failure: true
max_retries: 2
save_detailed_logs: true
output_format: "json"  # "json", "csv", "html" 