# Jutge AI Model Benchmark Configuration
models:
  - name: "GPT-4o-mini"
    provider: "openai"
    model_id: "gpt-4o-mini"
    api_key: null  # Will use OPENAI_API_KEY environment variable
    max_tokens: 2000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "GPT-4o"
    provider: "openai"
    model_id: "gpt-4o"
    api_key: null  # Will use OPENAI_API_KEY environment variable
    max_tokens: 2000
    temperature: 0.1
    timeout: 30
    enabled: true

  - name: "Claude-3.5-Sonnet"
    provider: "anthropic"
    model_id: "claude-3-5-sonnet-20241022"
    api_key: null  # Will use ANTHROPIC_API_KEY environment variable
    max_tokens: 2000
    temperature: 0.1
    timeout: 30
    enabled: false  # Disabled by default, enable if API key is available

  - name: "Gemini-Pro"
    provider: "google"
    model_id: "gemini-pro"
    api_key: null  # Will use GOOGLE_API_KEY environment variable
    max_tokens: 2000
    temperature: 0.1
    timeout: 30
    enabled: false  # Disabled by default, enable if API key is available

problem_sets:
  hello_world:
    - "P68688_en"  # Hello world!

  basic_algorithms:
    - "P68688_en"   # Hello world!
    - "P62421_en"   # Three words
    - "P57548_en"   # Sum of two integer numbers
    - "P41221_en"   # Sum of three integer numbers
    - "P56118_en"   # Maximum of two integer numbers
    - "P52847_en"   # Maximum of three different integer numbers
    - "P90615_en"   # Maximum of three integer numbers
    - "P15613_en"   # Temperatures
    - "P48107_en"   # Integer division and remainder of two natural numbers

  medium_problems:
    - "P68688_en"   # Hello world!
    - "P62421_en"   # Three words
    - "P57548_en"   # Sum of two integer numbers
    - "P41221_en"   # Sum of three integer numbers
    - "P56118_en"   # Maximum of two integer numbers
    - "P90615_en"   # Maximum of three integer numbers
    - "P92351_en"   # Integer division and remainder of an integer number by a natural number
    - "P98960_en"   # Uppercase and lowercase letters
    - "P42042_en"   # Classification of characters (1)
    - "P90226_en"   # Comparison of words
    - "P92613_en"   # Rounding
    - "P37469_en"   # Time decomposition (1)
    - "P34279_en"   # Add one second
    - "P81629_en"   # Minimum change

  advanced_problems:
    - "P61634_en"   # Leap years
    - "P51126_en"   # Intervals (1)
    - "P56559_en"   # Intervals (2)
    - "P89265_en"   # Intervals (3)
    - "P58294_en"   # The answer
    - "P42042_en"   # Classification of characters (1)
    - "P37469_en"   # Time decomposition (1)
    - "P34279_en"   # Add one second
    - "P92351_en"   # Integer division and remainder of an integer number by a natural number
    - "P98960_en"   # Uppercase and lowercase letters

# Benchmark settings
max_attempts_per_problem: 1
timeout_per_problem: 300  # 5 minutes
retry_on_failure: true
max_retries: 2
save_detailed_logs: true
output_format: "json"  # "json", "csv", "html"
parallel_strategy: "full"  # "full", "models", "sequential" 